version: '3.8'
services:
    orderapiv1:
        image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "Test@1234"
            MSSQL_PID: Express
        ports:
            - "1433:1433"
    employeeapi:
        image: damish/employeeapi-employeeapi
        depends_on:
            - orderapiv1
        environment:
            ServerName: "orderapiv1"
            Database: "Employee"
            UserName: "SA"
            Password: "Test@1234"
        ports:
            - "1337:80"
